project:
  type: website

website:
  title: 生产制造 | Production Industry
  favicon: /image/logo.svg
  navbar:
    tools:
      - href: https://www.pengxianzhe.org
        icon: house-door
    search: true
format:
  html:
    theme: flatly
    css: styles.css
    fontsize: 18px
    linestretch: 1.6
    date-format: "YYYY 年 M 月 DD 日"
    toc: true
    toc-depth: 3
    lang: zh
    language:
      zh:
        Abstract: 摘要



