project:
  type: website

website:
  title: 生产制造 | Production Industry
  favicon: /image/logo.svg
  navbar:
    tools:
      - icon: link
        menu:
          - text: 返回域名主页
            href:  https://academic.pengxianzhe.org
          - text: 微信公众平台个人号
            href:  https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzkwNTMwNzI1Mw==
      - href: /
        icon: house-door
    search: true
format:
  html:
    theme: flatly
    css: styles.css
    fontsize: 1.2em
    linestretch: 1.5



