project:
  type: website

website:
  title: 生产制造 | Production Industry
  favicon: /image/logo.svg
  navbar:
    tools:
      - href: https://www.pengxianzhe.org
        icon: house-door
    search: true
format:
  html:
    theme: flatly
    css: styles.css
    fontsize: 1.2em
    linestretch: 1.5



